import styles from './index.module.css';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import { api } from '~/utils/api';
import dynamic from 'next/dynamic';
import { GameWrapper } from '~/components/game/GameWrapper';
import { Stage } from '@pixi/react';
import { Game } from '~/components/game/Game';

// const GameWrapper = dynamic(
// 	() => import('~/components/game/GameWrapper').then((mod) => mod.GameWrapper),
// 	{
// 		ssr: false,
// 	}
// );

export default function Home() {
	// const hello = api.example.hello.useQuery({ text: 'from tRPC' });

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta
					name='description'
					content='Generated by create-t3-app'
				/>
				<link
					rel='icon'
					type='image/svg+xml'
					href='/favicon/favicon.svg'
				/>
			</Head>

			<main className={styles.main}>
				<GameWrapper />
				{/* <Stage>
					<Game />
				</Stage> */}
			</main>
		</>
	);
}

// function AuthShowcase() {
// 	const { data: sessionData } = useSession();

// 	const { data: secretMessage } = api.example.getSecretMessage.useQuery(
// 		undefined, // no input
// 		{ enabled: sessionData?.user !== undefined }
// 	);

// 	return (
// 		<div className={styles.authContainer}>
// 			<p className={styles.showcaseText}>
// 				{sessionData && <span>Logged in as {sessionData.user?.name}</span>}
// 				{secretMessage && <span> - {secretMessage}</span>}
// 			</p>
// 			<button
// 				className={styles.loginButton}
// 				onClick={sessionData ? () => void signOut() : () => void signIn()}
// 			>
// 				{sessionData ? 'Sign out' : 'Sign in'}
// 			</button>
// 		</div>
// 	);
// }
